"""make generated_code nullable

Revision ID: 2a14458e5769
Revises: 3b6f9b108c18
Create Date: 2026-04-05 19:16:44.257947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a14458e5769'
down_revision: Union[str, Sequence[str], None] = '3b6f9b108c18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_generations', 'generated_code',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_comment='Сгенерированный код')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('code_generations', 'generated_code',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_comment='Сгенерированный код')
    # ### end Alembic commands ###
