"""msg

Revision ID: 3b6f9b108c18
Revises: 
Create Date: 2026-04-05 17:22:48.399833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6f9b108c18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Хеш пароля (bcrypt/argon2)'),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('code_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.Text(), nullable=False, comment='Запрос пользователя'),
    sa.Column('generated_code', sa.Text(), nullable=False, comment='Сгенерированный код'),
    sa.Column('language', sa.String(), nullable=False, comment='Язык кода'),
    sa.Column('model_name', sa.String(length=50), nullable=False, comment='Использованная LLM'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='Температура генерации'),
    sa.Column('context_length', sa.Integer(), nullable=False, comment='Размер контекста (num_ctx)'),
    sa.Column('validation_status', sa.Enum('PENDING', 'SUCCESS', 'SYNTAX_ERROR', 'LINT_ERROR', 'FAILED', 'RETRY', name='generation_status'), nullable=False, comment='Результат валидации кода'),
    sa.Column('validation_log', sa.Text(), nullable=True, comment='Вывод luac/luacheck или ошибка'),
    sa.Column('attempts_count', sa.Integer(), nullable=False, comment='Количество попыток генерации/исправления'),
    sa.Column('tokens_prompt', sa.Integer(), nullable=True, comment='Токенов в промпте'),
    sa.Column('tokens_completion', sa.Integer(), nullable=True, comment='Токенов в ответе'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Время генерации в мс'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_model', 'code_generations', ['model_name'], unique=False)
    op.create_index('idx_status', 'code_generations', ['validation_status'], unique=False)
    op.create_index('idx_user_created', 'code_generations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_code_generations_created_at'), 'code_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_code_generations_id'), 'code_generations', ['id'], unique=False)
    op.create_index(op.f('ix_code_generations_user_id'), 'code_generations', ['user_id'], unique=False)
    op.create_index(op.f('ix_code_generations_validation_status'), 'code_generations', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_generations_validation_status'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_user_id'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_id'), table_name='code_generations')
    op.drop_index(op.f('ix_code_generations_created_at'), table_name='code_generations')
    op.drop_index('idx_user_created', table_name='code_generations')
    op.drop_index('idx_status', table_name='code_generations')
    op.drop_index('idx_model', table_name='code_generations')
    op.drop_table('code_generations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
